### ISSUE TITLE
Ошибка скачивания youtube

### ISSUE THREAD

**Issue by Waiker** [s-n-alexeyev/yvt#1]
Здравствуйте. Пытаюсь использовать ваш скрипт.
Т.к используется yt-dlp предполагаю что не дожно быть проблем и ссылками youtube.
Пробую выполнить ваш скрипт с видео из youtube, но после скачивания файла получаю ошибку - просто FAIL/

Возможно это связано с особенностями формата и кодеков при скачивании с yotutube. Пробовал указать для скачивания yt-dlp параметры `-S vcodec:h264` . Это не помогло. 
Прошу помочь.

**Comment by s-n-alexeyev** [comment]
Доброго времени суток
Зависимости все установлены?
Ссылки должны быть в кавычках
желательно скрин приложить чтобы было понятно

**Comment by Waiker** [comment]
да. файл скачивается, но когда скрипт доходит до ffmpeg - начинаются проблемы. Мне, к сожалению, опыта для отладки не хватает. По скрину мало что понятно)
![image](https://github.com/s-n-alexeyev/yvt/assets/5464086/7d49a862-eb10-46b6-9585-5d7548445891)

Строки "h264 aac" я добавлял для отладки.

**Comment by s-n-alexeyev** [comment]
так вроде все понятно, пишет что нужно использовать другую ссылку не для Android

**Comment by Waiker** [comment]
я использую обычную ссылку с браузера ПК. Файл успешно скачивается по ссылке. Проблемы начинаются когда ffmpeg начинает работать с файлом

**Comment by s-n-alexeyev** [comment]
![image](https://github.com/s-n-alexeyev/yvt/assets/133627370/1340853b-b9e8-4b4d-961a-98e78b86a61e)
У меня все сработало на ура.
Можно в скрипте закомментировать все  
```
    tput cuu1
    tput el
```
чтобы было видно весь процесс

**Comment by Waiker** [comment]
Странно. Какая у вас версия yt-dlp ? 
У меня: 
```
yt-dlp --version
2024.04.09
```

**Comment by Waiker** [comment]
![image](https://github.com/s-n-alexeyev/yvt/assets/5464086/9b4e5229-13a8-426c-9b0e-02bb00ad4e4a)
У меня и энкодер другой почему-то

**Comment by s-n-alexeyev** [comment]
дело в энкодере, если выбран софтверный (libx264), то дает такую ошибку
с энкодером h264_nvenc, все отрабатывает
надо подумать почему так
h264_nvenc - nVidia энкодер

**Comment by Waiker** [comment]
Да, сменил кодек в 262 строке на `h264_nvenc` и все заработало.
Я потратил на это несколько часов((

**Comment by s-n-alexeyev** [comment]
странно, если видеокарта от nVidia, то и так должно было сработать, а если другая, libx264

**Comment by s-n-alexeyev** [comment]
lspci | grep -iE "vga.*nvidia|nvidia.*vga"
что выдает в консоли?

**Comment by Waiker** [comment]
> lspci | grep -iE "vga.*nvidia|nvidia.*vga" что выдает в консоли?

ничего. Карта nvidia 1060 6gb.
Ubuntu 20.04.3 LTS

**Comment by s-n-alexeyev** [comment]
еще более странно, у меня тоже 1060
![image](https://github.com/s-n-alexeyev/yvt/assets/133627370/316dc3d9-4258-4412-9374-39b1392f000d)

**Comment by Waiker** [comment]
у меня виртуалка, видимо с этим связано. 

p/s еще на выходе получается видео с большой потерей качества, как не так сильно терять в качестве ?

**Comment by s-n-alexeyev** [comment]
качество плохое, потому что низкий битрейт, надо 1000-2000, 450 - хорошо для вебинаров, где демонстрируют экран

**Comment by s-n-alexeyev** [comment]
lspci | grep -iE "nvidia" что дает?

**Comment by Waiker** [comment]
> lspci | grep -iE "nvidia" что дает?

ничего

**Comment by s-n-alexeyev** [comment]
ок
тогда весь lspci покажи

**Comment by Waiker** [comment]
![image](https://github.com/s-n-alexeyev/yvt/assets/5464086/4b40329d-96a9-4137-823b-7ede2275b517)

**Comment by s-n-alexeyev** [comment]
ясно, под виртуалкой не работает как надо

**Comment by s-n-alexeyev** [comment]
винда - зло ;)

**Comment by Waiker** [comment]
> винда - зло ;)

)) Спасибо что помог разобраться!

**Comment by s-n-alexeyev** [comment]
у меня в репозитории есть накопленная база знаний для Obsidian, по винде тоже кое-что есть
https://github.com/s-n-alexeyev/Obsidian
