### ISSUE TITLE
Ошибка при сохранении файла

### ISSUE THREAD

**Issue by Waiker** [s-n-alexeyev/yvt#2]
Здравствуйте. Скриптом пользуюсь каждый день. Сегодня стал получать ошибку при сохранении файла
![image](https://github.com/s-n-alexeyev/yvt/assets/5464086/7255a7d5-8cda-4501-b612-86ad563e4209)

Неважно что я отвечу **y** или **N** - получаю ответ FAIL и скрипт заканчивает работу.

Если для скачивания указываю ссылку на youtube - проблем нет. Если yandex - то проблема как на скриншоте

@s-n-alexeyev

**Comment by imba-pericia** [comment]
Как-то странно, не сильно вникал, один раз после установки сработал, после аналогичная ошибка, по итогу удаляется темп и финальный файл не создается, cpu, libx264.
Помогло закомментировать 323:
```
        rm "$temp_video_dir/$video_full_name"
```
После стабильно работает, openSUSE Tumbleweed
